modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="icon.png"

[[mixins]]
config="growable_ores_touhou_little_maid_compat.mixins.json"

[[mods]]
modId="growable_ores_touhou_little_maid_compat"
version="${project.forge_mod_version}"
displayName="${project.mod_name}"
authors="${project.mod_authors}"

description='''${project.mod_description}'''

[[dependencies.growable_ores_touhou_little_maid_compat]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.growable_ores_touhou_little_maid_compat]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.growable_ores_touhou_little_maid_compat]]
modId="growable_ores"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.growable_ores_touhou_little_maid_compat]]
modId="touhou_little_maid"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"